translator:
  backend: 'deepl'
  source_lang: 'FR'
  target_lang: 'EN'
  tokens_file: 'tokens.txt'
  glossary: "glossaries/Bleach.json"
callbacks:
  - callback_name: CPSWarningCallback
    callback_args:
      max_cps: 21.
  - DialogueCallback
